### ISSUE TITLE
导出为图片时，标签显示异常

### ISSUE THREAD

**Issue by lixiao00093** [Achuan-2/siyuan-themes-tsundoku#101]
导出为图片时，显示如下：
![file-test](https://github.com/Achuan-2/siyuan-themes-tsundoku/assets/133181634/2a7313cd-15a7-4cc4-a58c-b3b34c760fa6)
中间多出来很多个#符号。我切换为默认主题时没有，说明是该主题的bug。
源文件也已上传：
[test.sy.zip](https://github.com/Achuan-2/siyuan-themes-tsundoku/files/14396470/test.sy.zip)

**Comment by Achuan-2** [comment]
谢谢反馈，已修复
![Clip_2024-02-25_22-36-54](https://github.com/Achuan-2/siyuan-themes-tsundoku/assets/60436214/f1f166d7-5818-4338-ad03-f1d9bb589c1a)
