### ISSUE TITLE
请问主题默认字体“汉仪空山楷”需要自行下载并添加代码片段吗？

### ISSUE THREAD

**Issue by isyngo** [Achuan-2/siyuan-themes-tsundoku#103]
你好，下载安装主题后，字体未发生变化，卸载重装也没有生效。

请问是否需要自行下载字体文件并添加代码片段，谢谢！

操作系统：win10
软件版本：3.0.6
主题版本：2.0.0

**Comment by Achuan-2** [comment]
主题没有默认字体，汉仪空山楷为推荐字体
需要自己下载并添加代码片段

**Comment by isyngo** [comment]
明白了，谢谢
