### ISSUE TITLE
题头图那里 图标没有适配，会遮住标题

### ISSUE THREAD

**Issue by lsb226** [Achuan-2/siyuan-themes-tsundoku#105]
如图
![image](https://github.com/Achuan-2/siyuan-themes-tsundoku/assets/16093704/1a69b12e-73c1-4fd4-8ffe-2c662f3451e2)

**Comment by Achuan-2** [comment]
谢谢反馈，最近主题代码样式改的太多了，我晚点更新

**Comment by Achuan-2** [comment]
![Clip_2024-04-30_23-22-25](https://github.com/Achuan-2/siyuan-themes-tsundoku/assets/60436214/7294e9f2-08de-4908-b5c9-45d671e70e86)
v2.0.6
