### ISSUE TITLE
标题提示圆点没有显示

### ISSUE THREAD

**Issue by Allen-Wang1997** [Achuan-2/siyuan-themes-tsundoku#107]
![image](https://github.com/Achuan-2/siyuan-themes-tsundoku/assets/53132988/f1da707c-85bf-4999-a786-bee80418b76d)

**Comment by Achuan-2** [comment]
你好，谢谢反馈
取消了这个功能了，觉得没有太大作用

**Comment by Achuan-2** [comment]
现在的主题设计会朝正式风格改进，所以会去除一些我认为的没必要元素，以及标题样式修改回较早的版本，
我现在是直接用本主题的样式复制到微信公众号发文章，以及导出pdf发小红书的，目前看来体验是比之前好的。

**Comment by Allen-Wang1997** [comment]
谢谢回复~ 我个人还是比较喜欢这个小圆点的设计，可以清晰的提示层级，不用鼠标悬停过去再查看。
不过现在这个版本不同层级标题的样式区别确实蛮大的，熟悉以后应该也能一眼认出层级。

**Comment by Achuan-2** [comment]
圆点适合所有标题都是一个颜色，用来区分
目前各级标题已经有很大差别，这个设计就重复了

**Comment by Achuan-2** [comment]
中文README已经添加了标题小圆点的代码片段，需要的可以自己添加
