### ISSUE TITLE
思源的分割线，变短和居中，可以调回来默认的分割线大小吗

### ISSUE THREAD

**Issue by Lazy188** [Achuan-2/siyuan-themes-tsundoku#108]
![Snipaste_2024-05-08_11-59-41](https://github.com/Achuan-2/siyuan-themes-tsundoku/assets/62982656/24605713-912c-4973-8b9b-dfef01aee837)

**Comment by Achuan-2** [comment]
谢谢反馈，个人觉得分割线变短居中的样式更好看，暂时不会调整
