### ISSUE TITLE
链接不显示网站icon

### ISSUE THREAD

**Issue by minilulubai** [Achuan-2/siyuan-themes-tsundoku#111]
你好啊，作者。
最新：v2.1.6版本，安装过：**链接图标** 这个插件，但不显示网页链接的所属网站的icon。
具体如下：
**当前不显示：**
![image](https://github.com/Achuan-2/siyuan-themes-tsundoku/assets/7126461/5ecc808f-e2e5-4c5b-882b-b208dee3967b)

**其他主题显示：**
![image](https://github.com/Achuan-2/siyuan-themes-tsundoku/assets/7126461/bf3e9ba2-75fc-4090-b86f-54c5d9fb4b2f)

还望定位下是否存在此类问题。谢谢。

**设备信息如下：**
![image](https://github.com/Achuan-2/siyuan-themes-tsundoku/assets/7126461/1ab57af0-de48-401d-9ad5-22580fd5c4d4)

**Comment by Achuan-2** [comment]
我这边没有用你说的链接图标插件是没有问题的
ps：预览模式和搜索界面主题默认是不显示链接图标的
![Clip_2024-05-31_12-55-23](https://github.com/Achuan-2/siyuan-themes-tsundoku/assets/60436214/b6f17eaf-6859-4c25-8414-812690ee19bf)

**Comment by minilulubai** [comment]
我把所有插件都关闭了，重新启动，选择这个主题，还是不显示。
新打开文件，模式：所见即所得模式。
不知道是不是Linux内核发行版上特有的问题。

![image](https://github.com/Achuan-2/siyuan-themes-tsundoku/assets/7126461/b2f3f6be-b877-4ca0-8bd6-bc598bbaa8b2)
![image](https://github.com/Achuan-2/siyuan-themes-tsundoku/assets/7126461/56522d33-5dd9-41d3-ad92-6e6bab949383)

**Comment by Achuan-2** [comment]
打开开发者工具，Ctrl+R刷新，如果依然这样就不了解了，看样子css是加载了，只是图标没有显示出来，不知道是不是路径问题
没有测试环境。

---

我大概知道了，Linux区分路径大小写，Windows不区分

**Comment by Achuan-2** [comment]
尝试修复了下，可以下载v2.1.7测试下
