### ISSUE TITLE
标题，自动添加标号，重复问题

### ISSUE THREAD

**Issue by HaoCeans** [Achuan-2/siyuan-themes-tsundoku#112]
正常添加标题，刷新后，自动添加标号，没有问题
![image](https://github.com/user-attachments/assets/1ce3099a-72a9-4c7b-a0a5-e7ff2290b7d7)

但是，当再次，在上面添加标题，刷新，标号就会重复
![image](https://github.com/user-attachments/assets/5930e569-af3f-4f4a-b0fb-5e7eceb710c6)

**Comment by HaoCeans** [comment]
无论是标题一、二、三、四...都是这样

**Comment by HaoCeans** [comment]
无法主动修改，表示难受

**Comment by Achuan-2** [comment]
应该去问插件作者吧。主题没有该功能

**Comment by HaoCeans** [comment]
好的








 ----------回复的邮件信息----------
 Jixiong ***@***.***&gt; 于2024年8月16日(周五) 上午10:34写道:

  

 
应该去问插件作者吧。主题没有该功能
