### ISSUE TITLE
数据库标签美化

### ISSUE THREAD

**Issue by keethebest** [Achuan-2/siyuan-themes-tsundoku#113]
如图，数据库标签的样式好像有点问题，太过紧凑感觉不够美观。建议是否能美化下

<img width="496" alt="image" src="https://github.com/user-attachments/assets/1d7723ea-039f-45e3-8023-4056e83e245e">

**Comment by Achuan-2** [comment]
已优化
![Clip_2024-08-31_23-05-17](https://github.com/user-attachments/assets/da69fe4c-ed38-4fff-9f2b-790315a542bd)
