### ISSUE TITLE
关于数据库主键的问题

### ISSUE THREAD

**Issue by Tisamn** [Achuan-2/siyuan-themes-tsundoku#115]
![1](https://github.com/user-attachments/assets/ca54d26a-f5b9-442c-beba-3c2096fdc82c)

版本更新后，被建立引用的主键无法实现换行了，默认主题可以正常换行，详见上图第二行~

**Comment by Achuan-2** [comment]
我这里没有问题
![PixPin_2024-10-07_08-24-47](https://github.com/user-attachments/assets/48be4517-52d0-4012-b450-c59a62ff015f)

**Comment by Tisamn** [comment]
> 我这里没有问题 ![PixPin_2024-10-07_08-24-47](https://private-user-images.githubusercontent.com/60436214/373990754-48be4517-52d0-4012-b450-c59a62ff015f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjgyNjI4MjgsIm5iZiI6MTcyODI2MjUyOCwicGF0aCI6Ii82MDQzNjIxNC8zNzM5OTA3NTQtNDhiZTQ1MTctNTJkMC00MDEyLWI0NTAtYzU5YTYyZmYwMTVmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDA3VDAwNTUyOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRkYTJiOWUyYWNkOGIwMjQ1ZjA1MjcyYWFlMzk2MTI4MjFkNWZjZjE0OTEyNjY3MDg0OWUwNzhkYTE0ZTQwNTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.jAu58lARvMSJzL8q0VrY8qcy6yAGRlaST1xG8sj3Stc)

前几天我这里也恢复正常了，不知道啥情况~
