### ISSUE TITLE
新版（3.1.8）思源中主题的“主题块样式更改”功能失效

### ISSUE THREAD

**Issue by loonghfut** [Achuan-2/siyuan-themes-tsundoku#116]
新版（3.1.8）思源中主题的“主题块样式更改”功能失效，即无法找到执行相关功能的按钮
更新前
![tmp542B](https://github.com/user-attachments/assets/8a87ed17-8d2b-4572-a8d4-e2a3a0cbd0a3)
更新后（思源3.1.8）
![tmpE168](https://github.com/user-attachments/assets/c4b72962-bd3f-4677-8ebf-6658e03980aa)

**Comment by loonghfut** [comment]
可能是因为3.1.8更新了[这个](https://ld246.com/forward?goto=https%3A%2F%2Fgithub.com%2Fsiyuan-note%2Fsiyuan%2Fpull%2F12559)

**Comment by Achuan-2** [comment]
谢谢反馈，已经修复
![PixPin_2024-10-09_22-41-12](https://github.com/user-attachments/assets/b98536f6-b2ee-4f42-b606-786abfb56bce)
