### ISSUE TITLE
黑暗模式下看板视图的文字对比度问题

### ISSUE THREAD

**Issue by loonghfut** [Achuan-2/siyuan-themes-tsundoku#117]
![tmp28B7](https://github.com/user-attachments/assets/9e2c2493-2172-4839-b849-a5cbbba41bb6)

第二级的字和周围的颜色对比度太低了，看起来比较费眼
建议：希望可以将二级的背景改为暗色调

最后：感谢您对上次处理问题的迅速响应

**Comment by Achuan-2** [comment]
![PixPin_2024-10-10_17-12-28](https://github.com/user-attachments/assets/56af9fd2-8ea4-4dd1-8be8-6a9b8c43a5fa)
已修复

**Comment by Achuan-2** [comment]
https://github.com/Achuan-2/siyuan-themes-tsundoku/commit/1a7ea3f35c655385e19ebb6ef06eca22c76f7990
