### ISSUE TITLE
深色主题加载问题

### ISSUE THREAD

**Issue by loonghfut** [Achuan-2/siyuan-themes-tsundoku#118]
使用网页版思源时如果网速较慢，主题加载会优先加载浅色模式，然后在显示深色模式，这样导致我一直用深色主题点击思源网页版会闪下白的，不知我的说法是否正确

使用其他暗色主题没有出现此问题

**Comment by loonghfut** [comment]
https://github.com/user-attachments/assets/b01845d9-da35-44f5-953b-c5195338d61f

**Comment by Achuan-2** [comment]
尝试修复了下，v2.3.7试试

**Comment by loonghfut** [comment]
> 尝试修复了下，v2.3.7试试

嗯，更新后没有问题了

**Comment by loonghfut** [comment]
最新版的主题似乎又有这个问题了

**Comment by loonghfut** [comment]
最新版的主题似乎又有这个问题了

**Comment by Achuan-2** [comment]
之前解决的方法是直接在theme.css删除浅色变量，但是这个存在一个问题，会导致预览模式导出到微信公众号没法用实际的css值
最新主题出现加载问题是我给export.css添加了浅色变量，现在已经去除了
现在是依然在theme.css放置root变量，但是把最影响外观的变量删除，也不影响导出到微信公众号

**Comment by loonghfut** [comment]
好的，感谢回复
