### ISSUE TITLE
可不可以改一下PDF导出的样式

### ISSUE THREAD

**Issue by Kikkwa** [Achuan-2/siyuan-themes-tsundoku#119]
PDF 导出的样式好像有一些问题，更改字体大小之后导出还是大的字体。其他的主题没有这个问题。
<img width="880" alt="image" src="https://github.com/user-attachments/assets/4f33b251-eb0b-495c-949f-8f8cfa451119">
并且能否改善一下标题间距，我想要打印出来复习记忆使用。这款主题的标题间距比其他主题都要大的多，不适合打印使用。

**Comment by Achuan-2** [comment]
尝试调整了下
pdf字体大小不能改是我之前为了发小红书，直接固定20px了，现在取消了，谢谢反馈

**Comment by Kikkwa** [comment]
> 尝试调整了下 pdf字体大小不能改是我之前为了发小红书，直接固定20px了，现在取消了，谢谢反馈

嗯嗯，谢谢回复
