### ISSUE TITLE
引述块折叠后直接只显示"blockquote"，而没有任何内容显示

### ISSUE THREAD

**Issue by boqxfjge** [Achuan-2/siyuan-themes-tsundoku#120]
完整内容为：
![完整显示](https://img.picui.cn/free/2024/11/15/6736fbd859f97.png)

隐藏后的显示
![隐藏显示](https://img.picui.cn/free/2024/11/15/6736fbd7c6ded.png)

默认主题隐藏后的显示
![默认](https://img.picui.cn/free/2024/11/15/6736fc8e03cf8.png)

期待的显示
![期待的显示](https://img.picui.cn/free/2024/11/15/6736fc8dd61d8.png)

希望可以支持callout隐藏后显示第一段内容。

**Comment by Achuan-2** [comment]
谢谢反馈，已经改进
![PixPin_2024-11-16_16-00-27](https://github.com/user-attachments/assets/a38f7368-5698-40c1-98f2-dd583c5b2797)
