### ISSUE TITLE
【问题】搜索框样式错乱

### ISSUE THREAD

**Issue by musnows** [Achuan-2/siyuan-themes-tsundoku#123]
思源版本3.1.3，搜索框样式会错乱，是当前主题版本已经不适配思源3.1.3了吗？

默认主题

<img width="1166" alt="image" src="https://github.com/user-attachments/assets/640ce164-85bb-495b-bebc-31365b95eed5" />

green主题

<img width="1173" alt="image" src="https://github.com/user-attachments/assets/bf2c9f58-af08-411b-876f-1655bbce5b3b" />

**Comment by musnows** [comment]
如下是临时解决方法，不确定是否通用。border-radius设置为10px

<img width="333" alt="image" src="https://github.com/user-attachments/assets/fdf44aa1-45dc-4627-acfc-a9634fd1b61e" />

<img width="1170" alt="image" src="https://github.com/user-attachments/assets/8587367f-72bc-4831-8560-465bf8b5a377" />

**Comment by Achuan-2** [comment]
![PixPin_2024-12-16_09-54-59](https://github.com/user-attachments/assets/5bf4e956-063d-4f1d-a61e-780a706a3efa)
https://github.com/Achuan-2/siyuan-themes-tsundoku/commit/026ec4651b3ee2506e2bf432ded441d4f43f226d
圆角暂时取消了

**Comment by Achuan-2** [comment]
另外主题一定是跟着思源笔记最新版本走的
比如思源笔记v3.1.15改进了搜索高亮方法，之前搜索界面我是取消了link icon的，因为原来的高亮样式会把链接拆成多个，一个链接可能会出现多个link icon，但现在思源笔记改进了之后，搜索的高亮是不影响link icon样式的，又加上了。但思源笔记旧版就依然有这个问题
