### ISSUE TITLE
暗色模式下链接的图标颜色没有调整

### ISSUE THREAD

**Issue by 2016201256** [Achuan-2/siyuan-themes-tsundoku#13]
![image](https://user-images.githubusercontent.com/58763608/141685294-0f8db309-c533-45d3-9111-170298d4badd.png)
![image](https://user-images.githubusercontent.com/58763608/141685303-2a8a10da-4739-4524-a4fa-b88bd8f8ada4.png)
暗色模式下图标是黑的

**Comment by Achuan-2** [comment]
你好，我本地的主题是正常的
![image](https://user-images.githubusercontent.com/60436214/141685462-81388ad7-aa14-4bf1-85c3-7837d70a000c.png)

**Comment by 2016201256** [comment]
嗯嗯不好意思, 从集市里安装主题就好了. 刚才下载文件放到主题文件夹里就出现这种情况.
