### ISSUE TITLE
Markdown源代码功能bug

### ISSUE THREAD

**Issue by lesir831** [Achuan-2/siyuan-themes-tsundoku#61]
块菜单右键点击编辑**Markdown源代码**和**编辑Kramdown源代码**都会显示**404 page not found**

**Comment by Achuan-2** [comment]
已修复，见1.5.6

**Comment by lesir831** [comment]
> 

思源的商店还未更新，我下载release下的zip手动替换主题还是显示的这个，是我的操作有问题？

**Comment by Achuan-2** [comment]
打开开发者工具，f5刷新后再看看

**Comment by lesir831** [comment]
我把console里link的Tsundoku%20Green换成Dark+就可以打开了（我装了Dark+，它的功能是正常）

**Comment by Achuan-2** [comment]
能告知是改动哪里吗， 我下载了1.5.6的并没有发现问题

**Comment by Achuan-2** [comment]
修复了下，如果有空可以测试下：https://github.com/Achuan-2/siyuan-themes-tsundoku/releases/tag/v1.5.7

**Comment by lesir831** [comment]
感谢，已修复
