### ISSUE TITLE
块标符号不消失

### ISSUE THREAD

**Issue by tcmtom** [Achuan-2/siyuan-themes-tsundoku#63]
https://user-images.githubusercontent.com/94541098/220325390-0d625d01-7c98-4da7-870b-320ea1ae3bf8.mp4

已在默认主题下测试无此问题

**Comment by Achuan-2** [comment]
谢谢老铁反馈❤https://github.com/Achuan-2/siyuan-themes-tsundoku/commit/c491e79729591a5a97235e55bb1fa45e1b8cfa4e

**Comment by tcmtom** [comment]
https://user-images.githubusercontent.com/94541098/220533149-23ef522b-3d30-4de1-8417-a7f2c395f049.mp4


大佬，更新之后还是能复现
另外dark+的这个问题我已经反馈给萌新大佬修复了，希望您这边也能跟进修复一下https://github.com/Zuoqiu-Yingyi/siyuan-theme-dark-plus/issues/183
@Achuan-2

**Comment by Achuan-2** [comment]
我这边暂时已经没有这个问题了

**Comment by tcmtom** [comment]
> 我这边暂时已经没有这个问题了

卸载重装之后好了

**Comment by Achuan-2** [comment]
好的

**Comment by Achuan-2** [comment]
@tcmtom Dark+的问题，直接复制代码了。https://github.com/Achuan-2/siyuan-themes-tsundoku/commit/aa9f70975dc79b940ac0bd4d0a43e3b92be9b005

**Comment by tcmtom** [comment]
> @tcmtom Dark+的问题，直接复制代码了。[aa9f709](https://github.com/Achuan-2/siyuan-themes-tsundoku/commit/aa9f70975dc79b940ac0bd4d0a43e3b92be9b005)

好的大佬，直接复制新版的话不知道会不会有兼容的问题，我在本地只修改了65-70行的代码，现在是没问题的

**Comment by Achuan-2** [comment]
@tcmtom 我暂时用着没问题
