### ISSUE TITLE
选中文字的显示效果能改回原来的吗

### ISSUE THREAD

**Issue by tcmtom** [Achuan-2/siyuan-themes-tsundoku#64]
![图片](https://user-images.githubusercontent.com/94541098/220570279-f8d80820-7482-4db4-b4ec-89e673818d56.png)

这是原来的效果
![图片](https://user-images.githubusercontent.com/94541098/220570380-97bbb50a-4f44-40ad-8d94-c26729abea01.png)

这是新版的显示效果，看着还是原来的舒服
---
不改也行，改回原来的更舒服

**Comment by Achuan-2** [comment]
好的，谢谢。https://github.com/Achuan-2/siyuan-themes-tsundoku/commit/7bcb3a5d50b51a534345a8c5edfbab741e15558e
因为合并主题难免有些样式可能不匹配，需要慢慢调整
