### ISSUE TITLE
超链接icon显示错误

### ISSUE THREAD

**Issue by coderlemon17** [Achuan-2/siyuan-themes-tsundoku#65]
你好, 我更新tsundoku-light到最新版本之后, 发现超链接前本来显示的icon消失了, 请问您知道这个要怎么修复吗?

<img width="369" alt="52afca57a7966a80a915ad7c110909a" src="https://user-images.githubusercontent.com/39124095/221743875-b51caa09-0735-4f3c-b1a2-a55d600ad846.png">

思源版本: 2.7.6
Tsundoku-light版本: 1c0c2df596bb9844864ecef7f8b7eb904eb737e5 (tag: v1.6.0)

**Comment by Achuan-2** [comment]
ctrl+shift+i打开开发者工具，点击console控制台，按f5刷新看下

**Comment by coderlemon17** [comment]
![image](https://user-images.githubusercontent.com/39124095/221744354-0f7fb599-0864-4b7d-aa75-4a0fa053c758.png)
em, 但我check了一下icon什么的是有的, 
![image](https://user-images.githubusercontent.com/39124095/221744391-80b8a3f2-0984-41e4-889d-4ad249bebadd.png)

**Comment by Achuan-2** [comment]
f5刷新了吗

**Comment by coderlemon17** [comment]
刷新过了

**Comment by Achuan-2** [comment]
开发者工具那network那里需要勾上disable cahe。
或者把主题卸载再安装试试

**Comment by coderlemon17** [comment]
我想问一下咱们的repo是改名了吗, 我本地还是`appearance\themes\Tsundoku Light`, 但我看query里请求的是`\appearance\themes\Tsundoku`?

**Comment by coderlemon17** [comment]
我把本地的文件夹重命名之后显示正常了

**Comment by Achuan-2** [comment]
是的，改名了。集市里也改了
