### ISSUE TITLE
标签加上字体颜色后会导致标签的样式消失，变成普通文字样式。

### ISSUE THREAD

**Issue by gdy106** [Achuan-2/siyuan-themes-tsundoku#66]
没有带文字样式的标签：
![image](https://user-images.githubusercontent.com/57566668/222167134-a75f903e-138b-4f2a-beb5-92e44c65db54.png)

加粗样式的标签：
![image](https://user-images.githubusercontent.com/57566668/222167239-b3c10c93-31f2-4159-b01b-93c854c8a96c.png)

加底色的标签：
![image](https://user-images.githubusercontent.com/57566668/222167328-a931f189-82a2-4601-b389-2923966955c3.png)

改字色的标签：
![image](https://user-images.githubusercontent.com/57566668/222167440-d974ef57-ff06-4b2f-b7ce-51aef45fa6f2.png)

希望可以让标签样式不要被字体样式所覆盖。

**Comment by Achuan-2** [comment]
谢谢反馈，我之后看看

**Comment by Achuan-2** [comment]
已修复，现在支持给标签设置颜色了 
![image](https://user-images.githubusercontent.com/60436214/222946821-2b0a6f84-4132-49be-8f67-ccdfc8f13e8b.png)
