### ISSUE TITLE
搜索中的链接命中高亮会使链接多出一个链接标志符

### ISSUE THREAD

**Issue by tcmtom** [Achuan-2/siyuan-themes-tsundoku#68]
![图片](https://user-images.githubusercontent.com/94541098/223138336-78599ca9-65f9-41d0-aa8b-7c2285c8e276.png)

**Comment by Achuan-2** [comment]
这是思源为了让链接也能高亮的问题 ，被高亮的链接会分块，要解决要么siyuan改进，要么主题直接砍掉超链接图标了

**Comment by tcmtom** [comment]
> 这是思源为了让链接也能高亮的问题 ，被高亮的链接会分块，要解决要么siyuan改进，要么主题直接砍掉超链接图标了

明白了，那就先这样吧😂

**Comment by Achuan-2** [comment]
![image](https://user-images.githubusercontent.com/60436214/223140420-9243a08f-c370-4f49-98b1-40c900cdf829.png)
兼容下吧，搜索面板不显示link icon，编辑器才显示，我自己也很难受

**Comment by tcmtom** [comment]
> ![image](https://user-images.githubusercontent.com/60436214/223140420-9243a08f-c370-4f49-98b1-40c900cdf829.png) 兼容下吧，搜索面板不显示link icon，编辑器才显示，我自己也很难受

感谢大佬

**Comment by Achuan-2** [comment]
https://github.com/siyuan-note/siyuan/issues/7585
给思源提了这个意见，可以把代码删掉了 😂
