### ISSUE TITLE
打开的新窗口不能应用green配色

### ISSUE THREAD

**Issue by tcmtom** [Achuan-2/siyuan-themes-tsundoku#69]
![image](https://user-images.githubusercontent.com/94541098/224635806-2cb6f95b-e118-4c64-ac9b-7f53bfe12c65.png)

![image](https://user-images.githubusercontent.com/94541098/224635881-aa2006fd-ee0e-4451-81a4-46bacec75a2e.png)

如图

**Comment by Achuan-2** [comment]
已修复，不过因为需要读取当前是什么主题，所以有延迟
