### ISSUE TITLE
为H3（三级标题）设置字体颜色后，前缀小块导出PDF时无法生效

### ISSUE THREAD

**Issue by FlyChicken233** [Achuan-2/siyuan-themes-tsundoku#70]
![1](https://user-images.githubusercontent.com/107106881/227176651-04ecc20e-3060-44aa-bcf2-b54d72d2cfff.png)
![2](https://user-images.githubusercontent.com/107106881/227176683-7bcb3065-13e5-4f9d-a770-23b3b3363328.png)

**Comment by Achuan-2** [comment]
请问是最新版吗，我本地没有这个问题
![image](https://user-images.githubusercontent.com/60436214/227520265-5d8ae5e3-8ee4-4fdb-98f0-862df7afe93d.png)

**Comment by FlyChicken233** [comment]
> 请问是最新版吗，我本地没有这个问题 ![image](https://user-images.githubusercontent.com/60436214/227520265-5d8ae5e3-8ee4-4fdb-98f0-862df7afe93d.png)

![image](https://user-images.githubusercontent.com/107106881/227832714-75657886-d211-4fae-8000-4794b53a21b5.png)
我的思源是2.8.0最新版，Tsundoku更新到1.6.3，问题依旧；

![image](https://user-images.githubusercontent.com/107106881/227833028-e32f0dfe-c956-45ae-ba33-21cb7acbb6ab.png)
我还尝试了切换到以前的Tsundoku Light/Stone，均无此问题，不知道是怎么回事呢😢。

**Comment by Achuan-2** [comment]
你导出页面都和我不一样哦，我的右侧是白色的，你的是灰色的。或者打开开发者模式，然后在console面板按f5刷新下

**Comment by FlyChicken233** [comment]
尝试了上面操作，然后关闭外观-自定义，现在好了！原来是这个选项导致的。😝
这个主题是我用思源笔记以来最喜欢的，非常感谢！🤗

**Comment by Achuan-2** [comment]
感谢喜欢！思源自定义css会覆盖主题，可能是之前生成旧的代码导致这样吧，建议如果要自定义主题，custom.css只放要修改的片段，而不是一整个theme.css
