### ISSUE TITLE
悬浮窗口退出聚焦时，块进度条位置异常

### ISSUE THREAD

**Issue by gdy106** [Achuan-2/siyuan-themes-tsundoku#71]
![image](https://user-images.githubusercontent.com/57566668/228555511-d3bc8553-b470-476a-9691-af365d178a4a.png)

**Comment by Achuan-2** [comment]
您好，我这里无法复现

**Comment by gdy106** [comment]
> 您好，我这里无法复现

您好，我这里是稳定复现这个问题的，可参考下面的录屏。其他主题没有这个问题，所以应该不是我个人设置或者软件本身导致的。

https://user-images.githubusercontent.com/57566668/229160277-b76165d1-5690-4df6-bd8a-8ec7e723f74a.mp4

**Comment by Achuan-2** [comment]
已修复，等v1.6.4发布
