### ISSUE TITLE
反链面板显示被折叠的段落块异常。

### ISSUE THREAD

**Issue by MisakaImouto8912** [Achuan-2/siyuan-themes-tsundoku#76]
当引用块在段落块中时，如果该段落块的父级折叠了，则在反链面板中显示不出内容。
实测是主题问题。思源版本：v2.8.8.
复现截图如下
* 原主题：
  * 未折叠
![239731573-2b2a5a23-f648-490b-9eaf-1058c4f60010](https://github.com/Achuan-2/siyuan-themes-tsundoku/assets/47753140/bb267a68-3bd6-49c9-b27e-36afe5411ebe)

  * 折叠后，可以看到反链面板中文字颜色变浅了
![image](https://github.com/Achuan-2/siyuan-themes-tsundoku/assets/47753140/aa64f678-4bbb-4495-a9fe-3eaf7492bdb9)

* tsundoku 主题，折叠后截图
![微信图片_20230521171557](https://github.com/Achuan-2/siyuan-themes-tsundoku/assets/47753140/fb755dfc-fa8a-4f0c-83b6-d3e79717ff17)

**Comment by Achuan-2** [comment]
谢谢反馈，已修复
