### ISSUE TITLE
开启插件后，插件位置会到里面，还有就是取消了 主题扩展功能，竖线没有取消

### ISSUE THREAD

**Issue by lsb226** [Achuan-2/siyuan-themes-tsundoku#77]
![image](https://github.com/Achuan-2/siyuan-themes-tsundoku/assets/16093704/abd9e70c-0a52-4789-ac62-a7cc2e916009)

**Comment by lsb226** [comment]
有办法让插件在最右边吗

**Comment by lsb226** [comment]
还有个问题 就是主题处于暗黑模式的时候，切换成跟随系统好像没变化，当前操作系统是明亮的

**Comment by lsb226** [comment]
![image](https://github.com/Achuan-2/siyuan-themes-tsundoku/assets/16093704/61c7e481-955b-4dc8-ab34-c0b9a1454375)
另外 这里鼠标移上去能加个鼠标手势吗

**Comment by Achuan-2** [comment]
> 有办法让插件在最右边吗

这个位置是插件作者的设置，主题没法改，等思源支持顶栏自定义吧

**Comment by Achuan-2** [comment]
> 还有个问题 就是主题处于暗黑模式的时候，切换成跟随系统好像没变化，当前操作系统是明亮的

这个应该是思源的问题，我没用跟随系统过，默认主题有这个问题吗

**Comment by Achuan-2** [comment]
> ![image](https://user-images.githubusercontent.com/16093704/242820979-61c7e481-955b-4dc8-ab34-c0b9a1454375.png) 另外 这里鼠标移上去能加个鼠标手势吗

没懂

**Comment by Achuan-2** [comment]
竖线问题感谢反馈，已经删除了

**Comment by lsb226** [comment]
![image](https://github.com/Achuan-2/siyuan-themes-tsundoku/assets/16093704/37f4b757-939e-4559-a2ec-8ddc0abdc4e7)
就是这样，鼠标移上去 有手势出现
现在是这样的
![image](https://github.com/Achuan-2/siyuan-themes-tsundoku/assets/16093704/b122e03d-c1db-422d-a0af-d53109e5e0ce)

**Comment by Achuan-2** [comment]
参考pink room 主题添加了主题切换按钮，目前有鼠标手势了
