### ISSUE TITLE
很奇怪的替换 bug

### ISSUE THREAD

**Issue by tcmtom** [Achuan-2/siyuan-themes-tsundoku#79]
https://ld246.com/article/1683897582690

详见这个帖子，录频和数据这里面都有

**Comment by tcmtom** [comment]
2.9.1版本仍能复现

**Comment by Achuan-2** [comment]
周日再看看，最近没时间

**Comment by tcmtom** [comment]
> 周日再看看，最近没时间

不着急的，我只是跟进记录一下😉

**Comment by Achuan-2** [comment]
主题最新版，复现不出来

**Comment by tcmtom** [comment]
刚刚试了一下，还是能复现出来的
默认主题也试出来了，我再看看
