### ISSUE TITLE
绿色主题选项卡透明

### ISSUE THREAD

**Issue by hongdongjie** [Achuan-2/siyuan-themes-tsundoku#84]
![image](https://github.com/Achuan-2/siyuan-themes-tsundoku/assets/134572560/d8f7e10c-ede1-4406-b795-d33c722a9e99)
![image](https://github.com/Achuan-2/siyuan-themes-tsundoku/assets/134572560/1267c50f-eacf-48b3-bb50-90025edccb24)

**Comment by Achuan-2** [comment]
谢谢反馈，今晚测试完之后发布新版本
