### ISSUE TITLE
闪卡颜色与PDF引用颜色相同

### ISSUE THREAD

**Issue by LAD021** [Achuan-2/siyuan-themes-tsundoku#85]
我想实践渐进阅读，则需要大量在PDF标注上制作闪卡。但是两者的颜色是一样的，导致无法看清。
闪卡模板能不能做成边框有标注的类型，这样便于阅读闪卡内的内容。
<img width="739" alt="截屏2023-08-24 21 56 21" src="https://github.com/Achuan-2/siyuan-themes-tsundoku/assets/60390821/cd9046f5-f172-4adf-b2f1-ae0f468ba7e3">

**Comment by Achuan-2** [comment]
你好，本dark主题的闪卡样式是这样的
![Snipaste_2023-08-25_15-36-03](https://github.com/Achuan-2/siyuan-themes-tsundoku/assets/60436214/459a3d49-f0ad-46a1-8a96-92bc7cda773a)
并没有背景色，是不是修改了主题还是用了闪卡相关插件

**Comment by LAD021** [comment]
你好，确实是这样。我发现添加这个背景色是闪卡增强插件的渐进阅读功能添加的，快速制卡的时候不会添加背景色。
我决定去插件那边提个issue，看看能不能加个自定义摘录时对原文标注效果的设置
