### ISSUE TITLE
子弹线和导图插件有严重的冲突，建议做成可选项

### ISSUE THREAD

**Issue by frostime** [Achuan-2/siyuan-themes-tsundoku#90]
![image](https://github.com/mdzz2048/Lite/assets/27268127/1eb53d40-7c1e-47e4-9b27-163b6ddea1c6)

建议：

要么暂时去掉这个样式
要么和savor那样做成可选项目，可以打开也可以关闭（不过这个就会引入多余的 Js 了）

**Comment by Achuan-2** [comment]
已删除 https://github.com/Achuan-2/siyuan-themes-tsundoku/commit/15d852956bda3998b65c6b1be5fefea67af1ef3c
可以参考这篇文章 https://ld246.com/article/1693238082034
添加代码片段以启用
