### ISSUE TITLE
link_icon.css: make editing laggy

### ISSUE THREAD

**Issue by hep-cogth** [Achuan-2/siyuan-themes-tsundoku#91]
To reproduce: quickly add multiple list.

**Comment by Achuan-2** [comment]
To be honest, I did not reproduce this issue

**Comment by hep-cogth** [comment]
It boils down to performance regression caused by Linux GUI Stack.
Sorry for insufficient investigation.

**Comment by Achuan-2** [comment]
It's okay, thank you for your feedback
