### ISSUE TITLE
好像v2.12.0下有错误

### ISSUE THREAD

**Issue by xibaoning** [Achuan-2/siyuan-themes-tsundoku#93]
如题, 以前没注意,今天更新后F12有错误
theme.js?v=1.8.7:778  Uncaught (in promise) ReferenceError: bulletMain is not defined
    at theme.js?v=1.8.7:778:5
    at theme.js?v=1.8.7:780:3
(anonymous) @ theme.js?v=1.8.7:778
(anonymous) @ theme.js?v=1.8.7:780
app.230201.js:346 [日历插件][Info] currentNotebook is [日记本]
app.230201.js:389 [日历插件][info] 成功读取用户配置 | 读取日记本【日记本】的 模板路径 为 /daily note/{{now | date "2006/01"}}/{{now | date "2006-01-02"}}
app.230201.js:401 [日历插件][info] 替换为当前日期的模板变量 /daily note/${e[0]}/${e[1]}/${e[0]}-${e[1]}-${e[2]} 其中e为形如[2021, 10, 27]的当前日期变量

**Comment by Achuan-2** [comment]
谢谢反馈，我今天也注意到了，因为之前加了子弹线，后来删了，没删干净……

**Comment by Achuan-2** [comment]
v1.8.8已经解决了
