### ISSUE TITLE
标题的颜色为啥没有了

### ISSUE THREAD

**Issue by ethan1010** [Achuan-2/siyuan-themes-tsundoku#94]
标题的颜色为啥没有了

原来的挺好的，信息比较多的时候，可以一眼看到标题。我就是为了这个采用这个主题的

**Comment by Achuan-2** [comment]
请问您说的是二级标题还是三级标题呀，二级标题的颜色确实取消了，因为我个人的喜好一直在变哈哈哈
三级标题是加了背景色的
<img width="752" alt="Snipaste_2024-01-04_10-38-19" src="https://github.com/Achuan-2/siyuan-themes-tsundoku/assets/60436214/8d43ee10-cbfc-40c5-b932-7d08f924fac2">

**Comment by convforper** [comment]
如果引述块或段落加了背景颜色，跟标题这块的颜色就区分不开了，确实觉得没有之前清楚明了，问题主要在3，4级这两个标题的样式跟引述块或段落背景颜色太接近，蓝色和绿色却是常用的背景颜色


![Dingtalk_20240106202452](https://github.com/Achuan-2/siyuan-themes-tsundoku/assets/7939305/2d7d4f25-590e-4a03-93d2-71522b1df42f)

而以前的则不会
![Dingtalk_20240106203805](https://github.com/Achuan-2/siyuan-themes-tsundoku/assets/7939305/58dcda25-f780-4f27-b26b-cf0a71c7f597)



@Achuan-2

**Comment by Achuan-2** [comment]
谢谢反馈，我也发现了这个问题，还在想怎么改 @convforper

**Comment by Achuan-2** [comment]
@convforper  改了下背景色、添加了一点阴影、添加了savor的标题提示, 这样会不会好一些
![Clip_2024-01-07_13-23-14](https://github.com/Achuan-2/siyuan-themes-tsundoku/assets/60436214/fdc17179-1ca5-4489-a9a4-d6fb45cfb7de)

**Comment by convforper** [comment]
@Achuan-2 要好一些吧，我自己倒是蛮喜欢V1.8.2版本的样式的
![screenshot-20240108-222717](https://github.com/Achuan-2/siyuan-themes-tsundoku/assets/7939305/446c8a20-019c-4e53-a41d-82f799835b26)

**Comment by Achuan-2** [comment]
> @Achuan-2 要好一些吧，我自己倒是蛮喜欢V1.8.2版本的样式的 ![screenshot-20240108-222717](https://private-user-images.githubusercontent.com/7939305/294933067-446c8a20-019c-4e53-a41d-82f799835b26.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ3MjQzOTIsIm5iZiI6MTcwNDcyNDA5MiwicGF0aCI6Ii83OTM5MzA1LzI5NDkzMzA2Ny00NDZjOGEyMC0wMTljLTRlNTMtYTQxZC04MmY3OTk4MzViMjYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDEwOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAxMDhUMTQyODEyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NGQ1MmFjY2M1M2ZhNDVlYzJiNzU3OWFjY2IzMzk3OWJkNmE4YzhkNjgzYjgwYjkxOTRjNTlkZTkyNjgzYzVhNCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.Pcac_zgqizdJ1BZmRIIltNXfzrGYx-OEdak6hCuKBIQ)

喜欢就继续用吧哈哈哈，审美这个，因人而异，而且也因时而异，我就是一会喜欢这个，一会喜欢那个的哈哈

**Comment by convforper** [comment]
@Achuan-2 嗯，最新版我也试一下看
