### ISSUE TITLE
Appreciation for Version 1.9.1 – A Significant Improvement! 🎉

### ISSUE THREAD

**Issue by mnyon** [Achuan-2/siyuan-themes-tsundoku#96]
This latest update has not only enhanced the functionality of the theme but has also significantly improved the overall user experience in Siyuan. pretty beautiful comment block style!
Thank you once again for your dedication and for continuously elevating the standards of this theme.

**Comment by Achuan-2** [comment]
Thank you so much for your kind words and positive feedback!
